language: node_js

matrix:
  include:
    - node_js: "0.10"
    - node_js: "0.12"
    - node_js: "iojs"
    - node_js: "4"
    - node_js: "5"

before_script:
- npm i

script: npm test

notifications:
  email: false