language: node_js

matrix:
  include:
    - node_js: "4"
    - node_js: "5"
    - node_js: "6"
    - node_js: "7"
    - node_js: "8"
    - node_js: "9"

before_script:
- npm i

script: npm test

notifications:
  email: false